### PR TITLE
add block `provisioner`

### PR DESCRIPTION
**Pull request by KiaraGrouwstra**

### CODE REVIEW

**Comment by KiaraGrouwstra** [comment]
hm, it looks like in the present state this PR has issues, seemingly clashing with the existing [`provider.nix`](https://github.com/terranix/terranix/blob/main/modules/provisioner.nix#L13).
running on a file that doesn't even use a `provisioner` block already triggers:

> error: The option `provisioner.privateKeyFile' is used but not defined.

as per the [docs](https://developer.hashicorp.com/terraform/language/resources/provisioners/syntax) i'm under the impression no such child appears mandatory.
i feel a bit confused about the existing presence of such an option there now.

**Comment by mrVanDalo** [comment]
Hmm I remember the provisioner part war quite tricky back than. It looks like provisioner is a code block which is missing in terranix.

I guess removing the provisioner.privateKeyFile is the solution here.

**Comment by mrVanDalo** [comment]
Actually I fixed the tests, pretty quick and it feels like it's ready to be merged.

**Comment by oneingan** [comment]
When exactly provisioner as first level block were introduced into terraform? Every documentation/blog I'm reading provisioners lives behind a resource block.

**Comment by mrVanDalo** [comment]
You are right. It seems I was to tired a few hours ago to realise.

Last time I used provisioners is to long ago.

Will revert, once I'm properly awake again.

**Comment by mrVanDalo** [comment]
Reverted this Pull Request.

**Pull request merged**
