### PR TITLE
Make resource and data referenceable - fixed (rebase)

### PR DESCRIPTION
**Pull request by mdarocha**
Rebase of https://github.com/terranix/terranix/pull/57, which I believe got erroneously closed without being merged.

It closes https://github.com/terranix/terranix/issues/43

### CODE REVIEW

**Comment by mdarocha** [comment]
Tests fail on CI, but I can't seem to view the logs. They pass locally for me.

**Comment by mdarocha** [comment]
@mrVanDalo any update for this PR?

**Comment by mrVanDalo** [comment]
> @mrVanDalo any update for this PR?

Sorry had no time to review so far.

**Comment by mdarocha** [comment]
I'll merge this to `develop` and test it, if any problems are encountered we can revert the changes (again :))

**Pull request merged**
